name: native_device_orientation
description: A Flutter plugin for reading device's native orientation
version: 0.4.0
homepage: https://github.com/rmtmckenzie/flutter_native_device_orientation

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0

flutter:
  plugin:
    androidPackage: com.github.rmtmckenzie.native_device_orientation
    pluginClass: NativeDeviceOrientationPlugin